### ISSUE TITLE
No entry 'bin\config.bin/CfgWeapons/ItemInfo.scope'

### ISSUE THREAD

**Issue by Cyruz143** [toadie2k/NIArms#19]
Since 1.62 BI have tightened up the inheritence rules, now the following error is thrown on load:

```
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.scope'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: Error: creating weapon ItemInfo with scope=private
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.displayName'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.nameSound'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.type'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.picture'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.Library'.
18:49:15 Warning Message: No entry '.libTextDesc'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.model'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.simulation'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.fireLightDuration'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.fireLightIntensity'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.fireLightDiffuse'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.fireLightAmbient'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.weaponLockDelay'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.weaponLockSystem'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.cmImmunity'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.weight'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.lockingTargetSound'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.lockedTargetSound'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.detectRange'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/ItemInfo.muzzles'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.scope'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: Error: creating weapon WeaponSlotsInfo with scope=private
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.displayName'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.nameSound'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.type'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.picture'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.Library'.
18:49:15 Warning Message: No entry '.libTextDesc'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.model'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.simulation'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.fireLightDuration'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.fireLightIntensity'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.fireLightDiffuse'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.fireLightAmbient'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.weaponLockDelay'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.weaponLockSystem'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.cmImmunity'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.weight'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.lockingTargetSound'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.lockedTargetSound'.
18:49:15 Warning Message: Size: '/' not an array
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.detectRange'.
18:49:15 Warning Message: '/' is not a value
18:49:15 Warning Message: No entry 'bin\config.bin/CfgWeapons/WeaponSlotsInfo.muzzles'.
18:49:15 Warning Message: Size: '/' not an array
```

Running the following code locally (thanks commy)

```
_r = configFile >> "CfgWeapons" >> "ItemInfo";

_w = "true" configClasses (configFile >> "CfgWeapons");
_w = _w select {inheritsFrom (_x >> "ItemInfo") == _r} apply {configName _x};

copyToClipBoard str _w;
```

Returns:
`["hlc_barrel_9mm"]`

So looks like something not quite defined correctly regarding the above. Kju gives an insight in to the correct config use here: https://forums.bistudio.com/topic/192259-config-errors-displaying/?p=3056311

**Comment by agorapolis** [comment]
I have the same problem ;)

**Comment by theYoursTruly** [comment]
Fixed with: https://github.com/toadie2k/NIArms/commit/22ff02e36f57f974a4d42dc0c972330384eea3c2

**Comment by theYoursTruly** [comment]
Actually, I'll keep it open for the rest of the weapons that are not on this GitHub yet.

**Comment by agorapolis** [comment]
Hello,

Do you plan to update the HLC's mods on Armaholic ?

**Comment by theYoursTruly** [comment]
Yes, no specific ETA yet though.

**Comment by nerdalertdk** [comment]
i'm just waiting on an combined version on steam that don't require CBA(CBA is bloated and an massive security risk on public server).

**Comment by jonpas** [comment]
@nerdalertdk You won't get one then, CBA will stay required. And it appears you are not very informed about what CBA is and how it works.

**Comment by nerdalertdk** [comment]
I know how CBA works, the only addon in CBA, niarms need its "JR" rest is just useless, CBA even adds event handles that is not needed, it have extended network stuff, which have no input validation and so on.

**Comment by commy2** [comment]
Please show how there is a security risk.

**Comment by nerdalertdk** [comment]
`[{ {_x setDamage 1 } count allPlayers }]call CBA_fnc_globalExecute``

**Comment by commy2** [comment]
You are wrong. With the same logic you use, this would also be a security risk:
`[allPlayers, { {_x setDamage 1 } count allPlayers }] remoteExec ["BIS_fnc_call"];`

**Comment by commy2** [comment]
In fact, `CBA_fnc_globalExecute` is a wrapper for `remoteExec`. No harm can be done with that function that can't be done with the `remoteExec` command

**Comment by nerdalertdk** [comment]
nope remoteExec is whitelisted in the CfgRemoteExec
https://community.bistudio.com/wiki/Arma_3_Remote_Execution#Security

**Comment by commy2** [comment]
Yes, but as I wrote, `CBA_fnc_globalExecute` is a wrapper for `remoteExec`

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/blob/master/addons/network/fnc_globalExecute.sqf#L57

You are wrong if you claim this is a security risk. Please don't spread unfounded rumors.

**Comment by nerdalertdk** [comment]
@jonpas i stand corrected, was last time i had to use cba, did not look at it again after.

but still bloated to add so many addons just to a scope on an gun
https://github.com/CBATeam/CBA_A3/tree/master/addons

**Comment by jonpas** [comment]
It is not bloated, CBA is the main addon providing dozens of frameworks and systems in a manner where it can easily be updated, fixed, improved .. etc, so different mods don't need to create their own systems, but rather use one made in CBA. Think of it as a library.

Either way, that is totally off-topic, so let's leave it at that, if you want to talk more about CBA you can head over to CBA repository.

**Comment by nerdalertdk** [comment]
when you only play epoch, exile, wasteland, koth it is :)

**Comment by alganthe** [comment]
Sure is when you play missions / mods made by people who don't even understand SQF properly (except sa-matra, he's nice)

**Comment by theYoursTruly** [comment]
Fixed for the other weapons.

**Comment by Cyruz143** [comment]
The following PBOs are still causing this issue:

```
hlc_CUP_Compat_AR15
hlc_CUP_Compat_AUG
hlc_CUP_Compat_M14
hlc_CUP_Compat_M60E4
hlc_CUP_Compat_MP5
hlc_ace3_compat_AUG
hlc_ace3_compat_MP5
```

**Comment by TheConen** [comment]
This is still happening for me, at least with the following PBOs:

```
hlc_wp_ak
hlc_wp_ar15
hlc_wp_aug
hlc_wp_FAL
hlc_wp_fhAWC
hlc_wp_g3
```

I didn't bother to test the rest of the PBOs, but I guess it's the same for them. All PBOs were freshly downloaded from the primary mirror from http://credmo.updatedtuesdays.com/tier1/products.

**Comment by toadie2k** [comment]
Yep, was about to say, mea culpa. Links on the pages are now all corrected.

**Comment by tradecraft1** [comment]
I'm still getting the same error with the V6 I pulled down from Armaholic. Do I need to do anything different?
